In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = df.apply(le.fit_transform)

In [7]:
# Create our features
X = df.drop(columns="loan_status")

# Create our target
y = df["loan_status"]

In [8]:
X.describe()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,dti,delinq_2yrs,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
count,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,572.296903,12.982577,4126.615168,1.812779,3294.087856,0.669994,0.805542,0.0,1962.376855,0.217722,...,367.820219,57.069314,0.125972,0.0,27710.412107,24184.046704,295.617696,19966.952715,0.0,0.0
std,375.779218,9.508701,2367.621789,0.941313,1574.576387,0.719105,0.714932,0.0,971.922012,0.717338,...,67.053040,55.878931,0.336732,0.0,17546.728857,14497.653994,257.292302,13661.709989,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25%,289.000000,5.000000,2153.000000,1.000000,1930.000000,0.000000,0.000000,0.0,1255.000000,0.000000,...,347.000000,0.000000,0.000000,0.0,12014.000000,11764.000000,116.000000,7895.000000,0.0,0.0
50%,516.000000,11.000000,3828.000000,1.000000,3365.000000,1.000000,1.000000,0.0,1842.000000,0.000000,...,409.000000,48.000000,0.000000,0.0,26735.000000,23056.000000,221.000000,18429.000000,0.0,0.0
75%,848.000000,20.000000,5967.000000,3.000000,4665.000000,1.000000,1.000000,0.0,2532.000000,0.000000,...,409.000000,101.000000,0.000000,0.0,42861.000000,36149.000000,393.000000,31243.000000,0.0,0.0
max,1397.000000,51.000000,8809.000000,3.000000,6089.000000,2.000000,2.000000,0.0,5695.000000,17.000000,...,409.000000,155.000000,4.000000,0.0,59628.000000,51997.000000,1715.000000,46898.000000,0.0,0.0

In [9]:
type(y)

pandas.core.series.Series

In [10]:
# Check the balance of our target values
y.value_counts()

1    68470
0      347
Name: loan_status, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
    y, random_state=1, stratify=y)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [12]:
# Resample the training data with the BalancedRandomForestClassifier
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=100, random_state=78)
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [13]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, predictions, sample_weight=None, adjusted=False)

0.6605398229731962

In [14]:
# Display the confusion matrix
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0           28           59
Actual 1           13        17105

In [15]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.68      0.32      1.00      0.44      0.57      0.30        87
          1       1.00      1.00      0.32      1.00      0.57      0.34     17118

avg / total       0.99      1.00      0.33      1.00      0.57      0.34     17205

In [16]:
# List the features sorted in descending order by feature importance
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.0763866355686389, 'total_rec_int'),
 (0.06869407015662418, 'last_pymnt_amnt'),
 (0.06799998040725516, 'total_pymnt_inv'),
 (0.061835187454468796, 'total_pymnt'),
 (0.061589943632831406, 'total_rec_prncp'),
 (0.01765191832256068, 'dti'),
 (0.01742975770261028, 'out_prncp'),
 (0.017386535917989724, 'out_prncp_inv'),
 (0.017348111274937773, 'installment'),
 (0.01691205100376104, 'mo_sin_old_il_acct'),
 (0.01625511144181331, 'total_bal_ex_mort'),
 (0.01623879439562318, 'max_bal_bc'),
 (0.01599334554949713, 'mo_sin_old_rev_tl_op'),
 (0.015667610268683768, 'bc_open_to_buy'),
 (0.015162872198094517, 'tot_cur_bal'),
 (0.014745972273288853, 'tot_hi_cred_lim'),
 (0.01466650331051024, 'bc_util'),
 (0.014512209412635162, 'total_bc_limit'),
 (0.014446790816818662, 'total_il_high_credit_limit'),
 (0.014377158473383698, 'annual_inc'),
 (0.013530860201734596, 'avg_cur_bal'),
 (0.013508613720807708, 'il_util'),
 (0.013374478518670994, 'total_rev_hi_lim'),
 (0.012837205195341895, 'revol_bal'),
 (0.012664234727699722, 'issue_d'),
 (0.012641554458625175, 'total_bal_il'),
 (0.012293433454857611, 'int_rate'),
 (0.012175926998065252, 'total_rec_late_fee'),
 (0.01194428135801404, 'mths_since_rcnt_il'),
 (0.01179969320345437, 'total_acc'),
 (0.01179502489172143, 'all_util'),
 (0.01109574561199111, 'mths_since_recent_inq'),
 (0.010950141530852222, 'mths_since_recent_bc'),
 (0.010783395689603504, 'mo_sin_rcnt_rev_tl_op'),
 (0.010394407191813499, 'open_acc'),
 (0.010274333284567458, 'num_il_tl'),
 (0.010243510316303486, 'acc_open_past_24mths'),
 (0.010219636263560945, 'num_rev_accts'),
 (0.010102126100319922, 'num_sats'),
 (0.009677082115904257, 'num_rev_tl_bal_gt_0'),
 (0.009631440235336018, 'loan_amnt'),
 (0.009547798539933013, 'num_actv_rev_tl'),
 (0.008806161746836228, 'num_bc_tl'),
 (0.00876753809634983, 'mo_sin_rcnt_tl'),
 (0.008751085645545768, 'num_actv_bc_tl'),
 (0.008672939336573638, 'num_op_rev_tl'),
 (0.008026808610489601, 'total_cu_tl'),
 (0.007830971581661857, 'inq_last_12m'),
 (0.007785859727661731, 'open_rv_24m'),
 (0.0076998834298293364, 'pct_tl_nvr_dlq'),
 (0.007644025460171223, 'percent_bc_gt_75'),
 (0.007198494555143759, 'open_acc_6m'),
 (0.007160011084771195, 'open_il_24m'),
 (0.00710547106820205, 'num_tl_op_past_12m'),
 (0.0069365658452666635, 'inq_fi'),
 (0.0066481533320855305, 'open_act_il'),
 (0.00625368609238945, 'num_bc_sats'),
 (0.005823917489713325, 'mort_acc'),
 (0.005620792243444245, 'open_il_12m'),
 (0.005493829249805115, 'open_rv_12m'),
 (0.004882395262614616, 'tot_coll_amt'),
 (0.0047578446954538636, 'inq_last_6mths'),
 (0.0045264986926417125, 'next_pymnt_d'),
 (0.004426594781219183, 'home_ownership'),
 (0.003711918808670258, 'delinq_2yrs'),
 (0.0034745083392330235, 'num_accts_ever_120_pd'),
 (0.003371089450011213, 'verification_status'),
 (0.0026314527401899673, 'pub_rec'),
 (0.0025260314549216123, 'pub_rec_bankruptcies'),
 (0.002098658661889622, 'collections_12_mths_ex_med'),
 (0.001627508361027222, 'num_tl_90g_dpd_24m'),
 (0.0013614813337878967, 'application_type'),
 (0.0013179963328371791, 'initial_list_status'),
 (0.0002743432983573968, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [17]:
# Train the EasyEnsembleClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1)

scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
from sklearn.ensemble import GradientBoostingClassifier
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
   classifier = GradientBoostingClassifier(n_estimators=100,
   learning_rate=learning_rate,
   random_state=0)
   classifier.fit(X_train_scaled, y_train)

In [22]:
# Calculated the balanced accuracy score
print("Learning rate:",learning_rate)
print("Accuracy score (training): {0:.3f}".format(
    classifier.score(
        X_train_scaled,
        y_train)))
print("Accuracy score (validation): {0:.3f}".format(
    classifier.score(
        X_test_scaled,
        y_test)))

Learning rate: 1
Accuracy score (training): 0.995
Accuracy score (validation): 0.994

In [23]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.9917465852949724

In [24]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
   cm, index=["Actual 0", "Actual 1"],
   columns=["Predicted 0", "Predicted 1"]
)
display(cm_df)

          Predicted 0  Predicted 1
Actual 0            0          101
Actual 1           41        17063

In [25]:
# Print the imbalanced classification report
print("Classification Report")
print(classification_report(y_test, predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       101
           1       0.99      1.00      1.00     17104

    accuracy                           0.99     17205
   macro avg       0.50      0.50      0.50     17205
weighted avg       0.99      0.99      0.99     17205